//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FusionBlock.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FusionBlock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib Fusion Block.mtl
        ///o GSO_Block_111
        ///v -0.417199 0.132427 -0.477527
        ///v -0.417199 -0.299595 -0.477527
        ///v -0.306088 -0.299595 -0.499749
        ///v -0.417199 -0.299595 0.478029
        ///v -0.483865 -0.299595 0.411362
        ///v -0.464113 -0.410706 -0.398515
        ///v -0.483866 -0.299595 -0.410860
        ///v -0.506088 -0.299595 -0.299749
        ///v -0.483866 -0.410706 -0.299749
        ///v -0.483865 -0.410706 0.300251
        ///v -0.506088 -0.299595 0.300251
        ///v -0.306088 -0.410706 -0.477527
        ///v 0.293912 -0.299595 -0.499749
        ///v 0.29 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fusion_Block {
            get {
                return ResourceManager.GetString("Fusion_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib Fusion Bolt.mtl
        ///o m_GSO_Exploder_A_111_Instance
        ///v -0.132000 -0.500000 -0.132000
        ///v 0.000000 -0.600000 -0.000000
        ///v -0.132000 -0.500000 0.132000
        ///v 0.132000 -0.500000 -0.132000
        ///v 0.132000 -0.500000 0.132000
        ///v 0.078901 -0.403218 0.078901
        ///v 0.000000 -0.286367 0.111582
        ///v 0.000000 -0.403218 0.111582
        ///v 0.078901 -0.286367 0.078901
        ///v 0.111583 -0.403218 -0.000000
        ///v 0.111583 -0.286367 -0.000000
        ///v 0.078901 -0.403218 -0.078901
        ///v 0.078901 -0.286367 -0.078901
        ///v  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fusion_Bolt {
            get {
                return ResourceManager.GetString("Fusion_Bolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib Fusion Plate.mtl
        ///o m_BF_Collector_111_Instance
        ///v -0.463982 -0.500000 -0.092292
        ///v -0.393345 -0.484188 -0.262824
        ///v -0.393345 -0.500000 -0.262824
        ///v -0.463982 -0.497146 0.000000
        ///v -0.262825 -0.484188 -0.393344
        ///v -0.092292 -0.484188 -0.463981
        ///v -0.096768 -0.402983 -0.421597
        ///v -0.068724 -0.353577 -0.391456
        ///v 0.092291 -0.500000 -0.463981
        ///v 0.092291 -0.484188 -0.463981
        ///v 0.262824 -0.484188 -0.393344
        ///v 0.393344 -0.484188 -0.262824
        ///v 0.387269 -0.465460 -0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fusion_Plate {
            get {
                return ResourceManager.GetString("Fusion_Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fusionblock_png {
            get {
                object obj = ResourceManager.GetObject("fusionblock_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fusionbolt_png {
            get {
                object obj = ResourceManager.GetObject("fusionbolt_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fusionplate_png {
            get {
                object obj = ResourceManager.GetObject("fusionplate_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
